### ISSUE TITLE
blacked doesn't work with black>=21.5b1 and crashes with latest versions

### ISSUE THREAD

**Issue by manfredlotz** [MrMrRobat/blacked#1]
I tried blacked with Python 3.10.2 and got

$ blacked somefile.py

```
Traceback (most recent call last):
  File "/home/manfred/.local/lib/python3.10/site-packages/blacked/__main__.py", line 75, in get_patched_black
    exec(f'from . import {PATCHED_BLACK_NAME}')
  File "<string>", line 1, in <module>
ImportError: cannot import name 'blacked22_1_0' from 'blacked' (/home/manfred/.local/lib/python3.10/site-packages/blacked/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/manfred/.local/bin/blacked", line 8, in <module>
    sys.exit(main())
  File "/home/manfred/.local/lib/python3.10/site-packages/blacked/__main__.py", line 121, in main
    patched_black = get_patched_black()
  File "/home/manfred/.local/lib/python3.10/site-packages/blacked/__main__.py", line 78, in get_patched_black
    rewrite_black()
  File "/home/manfred/.local/lib/python3.10/site-packages/blacked/__main__.py", line 86, in rewrite_black
    black_code = Path(black.__file__).read_text()
  File "/usr/lib/python3.10/pathlib.py", line 1133, in read_text
    return f.read()
  File "/usr/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 24: invalid start byte
```

**Comment by manfredlotz** [comment]
Same happens with Python 3.9.10. So it seems to be a general error in `blacked`

**Comment by Bobronium** [comment]
@manfredlotz, the issue boils down to the fact that `blacked` looks for `black` source code to copy it and rewrite, but newer versions of `black` seem to come pre-compiled, so it tries to read binary .so file, hence the error.

A solution would be to detect if black is currently compiled and search for .py file to rewrite, instead of the .so one. This also would mean that after making a blacked copy, compiled version of modified file needs to be either deleted, or recompiled with the changes.

*Upd.* It also seems that `black` done some refactoring, so latest supported version is 21.5b0. For a quick fix, just do `pip install black==21.5b0`. To support later versions, the library needs to be updated.

**Comment by manfredlotz** [comment]
Aah, ok. I didn't know how `blacked` works internally. Your suggestion using `black==21.5b0` is a good enough solution for me for the time being. Thanks for investigating.
